force-app/main/presentation-examples/2-data-source-example/objects/OpportunityLineItem/fields/Can_Be_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Can_Be_Cancelled__c</fullName>
    <formula>! ISPICKVAL( Fulfilment_Status__c, &apos;Fulfilled&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Can Be Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/presentation-examples/2-data-source-example/objects/OpportunityLineItem/fields/Cancelled_On__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_On__c</fullName>
    <label>Cancelled On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/presentation-examples/2-data-source-example/objects/OpportunityLineItem/fields/Fulfilment_Status__c.field-meta.xml
<CustomField>
    <fullName>Fulfilment_Status__c</fullName>
    <defaultValue>&quot;Not Ordered&quot;</defaultValue>
    <label>Fulfilment Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Ordered</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/presentation-examples/2-data-source-example/classes/OpportunityProductCanceller.cls
public with sharing class OpportunityProductCanceller {

    private DateTime dateOfCancellation = System.now();
    private OpportunityProductDataSource opportunityProductsDataSource;
    private List<OpportunityLineItem> opportunityProductsToUpdate;

    public OpportunityProductCanceller process() {

        opportunityProductsToUpdate = opportunityProductsDataSource.getProducts();

        for ( OpportunityLineItem thisProduct : opportunityProductsToUpdate ) {
            thisProduct.Fulfilment_Status__c = 'Cancelled';
            thisProduct.Cancelled_On__c      = dateOfCancellation;
        }
        return this;
    }

    public List<OpportunityLineItem> getProductsToUpdate() {
        return opportunityProductsToUpdate;
    }

    public OpportunityProductCanceller setProductsDataSource( OpportunityProductDataSource opportunityProductsDataSource ) {
        this.opportunityProductsDataSource = opportunityProductsDataSource;
        return this;
    }

    public OpportunityProductCanceller setDateOfCancellation( DateTime dateOfCancellation ) {
        this.dateOfCancellation = dateOfCancellation;
        return this;
    }




    public OpportunityProductCanceller processWithProtection() {

        opportunityProductsToUpdate = new List<OpportunityLineItem>();

        for ( OpportunityLineItem thisProduct : opportunityProductsDataSource.getProducts() ) {
            if ( thisProduct.Can_Be_Cancelled__c ) {
                thisProduct.Fulfilment_Status__c = 'Cancelled';
                thisProduct.Cancelled_On__c      = dateOfCancellation;
                opportunityProductsToUpdate.add( thisProduct );
            }
        }
        return this;
    }
}